const templates = [
  {
    id: 1,
    name: 'Modern CV Template',
    thumbnail: '/images/modern-cv.jpg',
    about: 'Desain CV modern yang cocok untuk berbagai profesi.',
    author_id: 1,
    category_id: 3,
    slug: 'modern-cv-template',
    price: 15,
    rating: 4.8,
  },
  {
    id: 2,
    name: 'Creative CV Template',
    thumbnail: '/images/creative-cv.jpg',
    about: 'Template CV dengan desain kreatif untuk pekerjaan di bidang seni.',
    author_id: 2,
    category_id: 2,
    slug: 'creative-cv-template',
    price: 20,
    rating: 4.5,
  },
  {
    id: 3,
    name: 'Professional CV Template',
    thumbnail: '/images/professional-cv.jpg',
    about: 'Desain CV profesional yang ideal untuk melamar posisi formal.',
    author_id: 3,
    category_id: 1,
    slug: 'professional-cv-template',
    price: 25,
    rating: 4.9,
  },
  {
    id: 4,
    name: 'Simple CV Template',
    thumbnail: '/images/simple-cv.jpg',
    about: 'Desain CV sederhana dan minimalis.',
    author_id: 4,
    category_id: 4,
    slug: 'simple-cv-template',
    price: 10,
    rating: 4.6,
  },
  {
    id: 5,
    name: 'Classic CV Template',
    thumbnail: '/images/classic-cv.jpg',
    about: 'Template CV dengan desain klasik yang tetap relevan.',
    author_id: 5,
    category_id: 5,
    slug: 'classic-cv-template',
    price: 18,
    rating: 4.7,
  },
]

export default templates
