export { default as Content } from './Content'
export { default as Navigation } from './Navigation'
export { default as Loader } from './Loader'
export { default as MovieList } from './MovieList'
export { default as Sidebar } from './Sidebar'
export { default as Slider } from './Slider'
export { default as Footer } from './Footer'
export { default as Title } from './Title'
